import { Inter } from "next/font/google";
import "./globals.css";
import NextUiProviders from "./nextUiProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="light" lang="en">
      <body className={inter.className}>
        <NextUiProviders>{children}</NextUiProviders>
      </body>
    </html>
  );
}
