import MainNavbar from "@/components/mainNavbar.jsx";

export const metadata = {
  title: "E-Football Game",
  description: "Generated by create next app",
};

export default function EFootballLayout({ children }) {
  return (
    <div>
      <MainNavbar />
      <div className="">
        <div className=" px-6">{children}</div>
      </div>
    </div>
  );
}
