import Navbar from "@/components/navbar/navbar";

export const metadata = {
  title: "E-Football Game",
  description: "Generated by create next app",
};

export default function EFootballLayout({ children }) {
  return (
    <div>
      <div className="max-w-[500px] border px-3 w-full mx-auto">
        <Navbar />
        <div>{children}</div>
      </div>
    </div>
  );
}
